AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ZipHash:
    Type: String

Resources:
  TransformPosition:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: asset2 
        S3Key: !Join
          - "/"
          - - "sss"
            - !Ref ZipHash
            - "deploy.zip"
          #ZipFile: deploy.zip
      Handler: main.transform_position_handler
      Runtime: python3.7 
      MemorySize: 128
      Role: arn:aws:iam::775706170440:role/test1-role
